# Generated by Django 6.0.2 on 2026-02-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='descricao',
        ),
    ]
